# server configurations
server:
  host: "http://127.0.0.1"
  port: 8081

# oauth configurations
oauth:
  issuer: "https://identity.io"
  rsa_bits: 2048
  jwt_ttl: "876000h"
  jwks: "/jwks"

# device grant configurations
device_grant:
  registration: "/device"
  user_code:
    ttl: "10m"
    length: 8

