# server configurations
server:
  host: "127.0.0.1"
  port: 8081

# oauth configurations
oauth:
  rsa_bits: 2048
  jwt_ttl: "60m"
  jwks: "/jwks"

# device grant configurations
device_grant:
  registration: "/device"
  user_code:
    ttl: "10m"
    length: 8

